#!/usr/bin/env python3
"""
TikTok -> Facebook Page auto-poster, via Buffer (Page A: storyflix11).

Flow:
  1. Round-robin across TIKTOK_PROFILES; for the current profile, fetch a
     small page of videos via yt-dlp starting at that profile's saved
     cursor (never the whole list — cheap even for huge profiles).
  2. Dedupe against state.json (by tiktok video_id). Once a page is fully
     posted, the cursor moves past it, so nothing gets re-checked or
     skipped. Once a profile's list is confirmed exhausted (hasMore=false
     with nothing new), move to the next profile and reset its cursor.
  3. Download the (no-watermark) video.
  4. Groq rewrites the TikTok caption into a fresh, niche-agnostic caption.
  5. Upload video to a public temp host (uguu.se) — Buffer's API requires
     a public media URL, it does not accept direct file uploads.
  6. Create the post on Buffer via its GraphQL API (createPost), which
     Buffer then publishes to the connected Facebook Page.
  7. Save dedupe/cursor state.

CHANGE FROM PREVIOUS VERSION:
  - No more direct Meta Graph API calls (no FB_SYSTEM_USER_TOKEN / page
    token exchange). Posting now goes through Buffer instead.
  - Instagram posting removed entirely — this Page isn't IG-linked, and
    Buffer treats FB/IG as separate channels anyway, so IG (if ever
    wanted) would be its own BUFFER_CHANNEL_ID + its own posting call,
    not bundled in here.

ENV VARS (GitHub Actions secrets):
  BUFFER_API_KEY     - Buffer personal API key (Buffer > developer settings,
                        must be generated by an org owner)
  BUFFER_CHANNEL_ID  - the Buffer channel ID for this Page's Facebook connection
  GROQ_API_KEY       - Groq API key
  GROQ_MODEL         - optional, default "llama-3.3-70b-versatile"
  MAX_VIDEOS         - optional, default 1 (videos posted per run)
  STATE_FILE         - optional, default "state.json"

REMOVED ENV VARS (no longer used, can delete these secrets):
  FB_SYSTEM_USER_TOKEN, FB_PAGE_ID

TikTok profiles are NOT a secret — edit TIKTOK_PROFILES below directly in
code.

Usage:
  python page_a_storyflix.py --dry-run   # test without posting
  python page_a_storyflix.py             # live run
"""

import os
import sys
import re
import json
import time
import argparse
import pathlib
import random
import requests
import yt_dlp

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
TIKTOK_PROFILES = [
    "storyflix11",
]

BUFFER_API_KEY = os.environ.get("BUFFER_API_KEY", "")
BUFFER_CHANNEL_ID = os.environ.get("BUFFER_CHANNEL_ID", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
MAX_VIDEOS = int(os.environ.get("MAX_VIDEOS", "1"))
DEDUPE_DIR = pathlib.Path(os.environ.get("DEDUPE_DIR", "dedupe"))
STATE_FILE = DEDUPE_DIR / os.environ.get("STATE_FILE", "state.json")
TMP_DIR = pathlib.Path("tmp_videos")
PAGE_SIZE = 5
MAX_PAGES_PER_RUN = 5

REQUIRED = {
    "BUFFER_API_KEY": BUFFER_API_KEY,
    "BUFFER_CHANNEL_ID": BUFFER_CHANNEL_ID,
    "GROQ_API_KEY": GROQ_API_KEY,
}


def check_env():
    missing = [k for k, v in REQUIRED.items() if not v]
    if missing:
        print(f"[FATAL] Missing env vars: {', '.join(missing)}")
        sys.exit(1)
    if not TIKTOK_PROFILES:
        print("[FATAL] TIKTOK_PROFILES list is empty — add at least one profile in the code.")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Dedupe / round-robin state
# ---------------------------------------------------------------------------
def load_state():
    DEDUPE_DIR.mkdir(parents=True, exist_ok=True)
    if STATE_FILE.exists():
        with open(STATE_FILE, "r", encoding="utf-8") as f:
            state = json.load(f)
    else:
        state = {}
    state.setdefault("current_profile_index", 0)
    state.setdefault("profiles", {})

    old_posted = state.pop("posted_ids", None)
    if old_posted:
        for p, ids in old_posted.items():
            state["profiles"].setdefault(p, {"cursor": 0, "posted_ids": []})
            existing = set(state["profiles"][p]["posted_ids"])
            state["profiles"][p]["posted_ids"] = list(existing | set(ids))

    for p in TIKTOK_PROFILES:
        state["profiles"].setdefault(p, {"cursor": 0, "posted_ids": []})

    return state


def save_state(state):
    DEDUPE_DIR.mkdir(parents=True, exist_ok=True)
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)


# ---------------------------------------------------------------------------
# TikTok fetch (yt-dlp)
# ---------------------------------------------------------------------------
def _ydl_opts(**extra):
    opts = {
        "quiet": True,
        "no_warnings": True,
        "skip_download": True,
        "http_headers": {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            )
        },
    }
    opts.update(extra)
    return opts


def list_profile_videos(profile):
    url = f"https://www.tiktok.com/@{profile}"
    with yt_dlp.YoutubeDL(_ydl_opts(extract_flat=True)) as ydl:
        info = ydl.extract_info(url, download=False)
    entries = info.get("entries") or []
    videos = []
    for e in entries:
        vid = e.get("id")
        if not vid:
            continue
        videos.append({
            "id": vid,
            "url": e.get("url") or e.get("webpage_url") or f"https://www.tiktok.com/@{profile}/video/{vid}",
        })
    return videos


def fetch_video_meta(video_url):
    with yt_dlp.YoutubeDL(_ydl_opts()) as ydl:
        info = ydl.extract_info(video_url, download=False)
    caption = (info.get("description") or info.get("title") or "").strip()
    return {"caption": caption}


def find_candidates(profile, pstate):
    all_videos = list_profile_videos(profile)
    if not all_videos:
        return [], True

    total = len(all_videos)
    cursor = pstate["cursor"]
    posted = set(pstate["posted_ids"])

    for _ in range(MAX_PAGES_PER_RUN):
        if cursor >= total:
            pstate["cursor"] = cursor
            return [], True

        page = all_videos[cursor:cursor + PAGE_SIZE]
        unposted = [v for v in page if v["id"] not in posted]

        if unposted:
            pstate["cursor"] = cursor
            candidates = []
            for v in unposted:
                meta = fetch_video_meta(v["url"])
                candidates.append({"id": v["id"], "caption": meta["caption"], "url": v["url"]})
            return candidates, False

        cursor += len(page)
        pstate["cursor"] = cursor
        if cursor >= total:
            return [], True

    return [], False


def download_video(video_url, dest_path):
    opts = _ydl_opts(
        skip_download=False,
        outtmpl=str(dest_path),
        format="bestvideo*+bestaudio/best",
        format_sort=["res", "fps", "br"],
        merge_output_format="mp4",
    )
    with yt_dlp.YoutubeDL(opts) as ydl:
        ydl.download([video_url])
    return dest_path


# ---------------------------------------------------------------------------
# Groq: niche-agnostic caption rewrite
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Fallback captions — used ONLY when the original TikTok caption has no
# usable text AND no hashtags (nothing for Groq to work with at all).
# ---------------------------------------------------------------------------
FALLBACK_CAPTIONS = [
    "Every scene tells a story worth watching.\n\n#MovieMoments #FilmClips #CinemaLovers #MustWatch #ScreenTime",
    "This is the kind of moment movies are made for.\n\n#MovieMagic #FilmLovers #CinemaClips #Hollywood #MustWatch",
    "Some scenes stay with you long after the credits roll.\n\n#ClassicMovies #FilmClips #CinemaLovers #MovieScenes #Unforgettable",
    "Great storytelling never goes out of style.\n\n#MovieMoments #FilmBuff #CinemaLovers #ClassicFilm #Storytelling",
    "A single scene, a thousand emotions.\n\n#FilmClips #MovieMagic #CinemaMoments #Hollywood #MustWatch",
    "This is why we fell in love with cinema.\n\n#MovieLovers #FilmClips #ClassicCinema #Hollywood #ScreenMoments",
    "Some stories deserve to be watched again and again.\n\n#MovieMoments #FilmClips #CinemaLovers #Rewatch #Hollywood",
    "The best scenes speak louder than words.\n\n#FilmMagic #MovieClips #CinemaLovers #Hollywood #Storytelling",
    "Cinema at its finest, one scene at a time.\n\n#MovieMoments #FilmLovers #ClassicCinema #Hollywood #MustWatch",
    "A moment worth pausing for.\n\n#FilmClips #MovieMagic #CinemaLovers #Hollywood #ScreenMoments",
]


def pick_fallback_caption():
    return random.choice(FALLBACK_CAPTIONS)


def generate_caption(original_caption, groq_key, model=GROQ_MODEL, max_words=15, max_attempts=3):
    original_caption = (original_caption or "").strip()
    hashtags_found = re.findall(r"#\w+", original_caption)
    text_only = re.sub(r"#\w+", "", original_caption).strip()
    text_only = re.sub(r"\s{2,}", " ", text_only)

    # Nothing usable at all — no text, no hashtags. Don't bother calling
    # Groq (it would just invent generic filler); pick a ready-made caption.
    if not text_only and not hashtags_found:
        print("[INFO] No usable text or hashtags in source caption — using fallback caption.")
        return pick_fallback_caption()

    if not text_only and hashtags_found:
        # No descriptive text, but hashtags give us a topic to work with.
        source_block = (
            "The original caption had NO descriptive sentence — only these "
            "hashtags: " + " ".join(hashtags_found) + "\n"
            "Use these hashtags ONLY as a clue to figure out the video's topic/theme, "
            "then write a natural caption about that theme. Do not mention that "
            "hashtags were your source."
        )
    else:
        source_block = f"ORIGINAL CAPTION:\n{original_caption}"

    base_prompt = (
        "You are a social media caption writer. You will be given the ORIGINAL "
        "caption from a TikTok video (any topic/niche — movie clips, film clip, etc). Rewrite it for Facebook/Instagram in the SAME "
        "language/tone as the original (if it's Hindi/Hinglish, reply in Hindi/Hinglish; "
        "if English, reply in English). Output in this EXACT format:\n\n"
        "<one punchy caption sentence>\n"
        "\n"
        "#hashtag1\n#hashtag2\n#hashtag3\n#hashtag4\n#hashtag5\n\n"
        "Strict rules:\n"
        f"- Line 1 is ONE sentence, MAXIMUM {max_words} words (count carefully — "
        "9 or 10 words is ideal, never go over the limit).\n"
        "- No emojis, no digits/numbers, in line 1.\n"
        "- Do NOT invent facts not present in the original caption.\n"
        "- Do NOT mention TikTok, any username/handle, video ID, or any TikTok-related "
        "word anywhere — the sentence must read naturally with no gaps or leftover "
        "words if such a mention were ever removed.\n"
        "- Then a blank line, then EXACTLY 5 hashtags, one per line.\n"
        "- Hashtags must be SEO-relevant to the actual content/niche of this video "
        "(not generic filler like #viral #trending #fyp) — think what someone would "
        "actually search to find this content. No spaces, no numbers, no repeats, "
        "no # symbol duplicated.\n"
        "- Output ONLY the caption + hashtags, nothing else (no preamble, no quotes, "
        "no explanation).\n\n"
        f"{source_block}"
    )

    prompt = base_prompt
    body_raw, hashtag_lines = "", []

    for attempt in range(1, max_attempts + 1):
        r = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {groq_key}"},
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.7,
                "max_tokens": 150,
            },
            timeout=30,
        )
        r.raise_for_status()
        raw = r.json()["choices"][0]["message"]["content"].strip()
        body_raw, hashtag_lines = split_caption(raw)

        if has_forbidden_terms(body_raw):
            prompt = (
                base_prompt
                + "\n\nYour previous attempt mentioned TikTok, a video ID, a handle, "
                  "or a number in line 1. Rewrite line 1 from scratch as a natural "
                  "sentence with NO such mentions and no leftover gaps."
            )
            continue

        body = clean_body(body_raw)
        if body and len(body.split()) <= max_words:
            break

        prompt = (
            base_prompt
            + f"\n\nYour previous attempt was too long. Rewrite line 1 to be "
              f"{max_words} words or fewer, same meaning, same format."
        )
    else:
        body = clean_body(body_raw)
        words = body.split()
        if len(words) > max_words:
            words = words[:max_words]
        body = tidy_dangling(" ".join(words))

    hashtags = clean_hashtags(hashtag_lines)
    if not hashtags:
        hashtags = fallback_hashtags(original_caption)

    return f"{body}\n\n" + "\n".join(hashtags)


def has_forbidden_terms(text):
    if re.search(r"(?i)\btik\s?tok\b", text):
        return True
    if re.search(r"(?i)\b(video|clip|post|reel)?\s*id\b", text):
        return True
    if re.search(r"@\w+", text):
        return True
    if re.search(r"\d", text):
        return True
    return False


def split_caption(raw):
    lines = [l.strip() for l in raw.splitlines() if l.strip()]
    body_lines, hashtag_lines = [], []
    for l in lines:
        if l.startswith("#"):
            hashtag_lines.append(l)
        else:
            body_lines.append(l)
    return " ".join(body_lines).strip(), hashtag_lines


def clean_body(body_raw):
    text = re.sub(r"(?i)\btik\s?tok\b", "", body_raw)
    text = re.sub(r"(?i)\b(video|clip|post|reel)?\s*id\b", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\s+([.,!?])", r"\1", text).strip()

    match = re.search(r"[^.!?]+[.!?]?", text)
    if match:
        text = match.group(0).strip()
    return text


def tidy_dangling(text):
    edge_words = {"by", "from", "on", "in", "at", "with", "to", "of", "the",
                  "a", "an", "and", "or", "this", "that", "for"}
    words = text.split()
    while words and words[-1].strip(".,!?").lower() in edge_words:
        words.pop()
    while words and words[0].lower() in edge_words:
        words.pop(0)
    text = " ".join(words).strip()
    if text:
        text = text[0].upper() + text[1:]
        if text[-1] not in ".!?":
            text += "."
    return text


def clean_hashtags(hashtag_lines):
    hashtags = []
    for l in hashtag_lines:
        hashtags.extend(re.findall(r"#\w+", l))

    seen, clean_tags = set(), []
    for h in hashtags:
        h = re.sub(r"[^A-Za-z#]", "", h)
        if len(h) > 1 and h.lower() not in seen:
            seen.add(h.lower())
            clean_tags.append(h)
    return clean_tags[:5]


def fallback_hashtags(original_caption):
    words = re.findall(r"[A-Za-z]{4,}", original_caption or "")
    stop = {"this", "that", "with", "from", "your", "have", "will", "just",
            "what", "when", "they", "them", "video", "watch", "tiktok"}
    seen, tags = set(), []
    for w in words:
        wl = w.lower()
        if wl in stop or wl in seen:
            continue
        seen.add(wl)
        tags.append("#" + w.capitalize())
        if len(tags) == 5:
            break
    generic_pool = ["#Explore", "#DailyDose", "#MustWatch", "#Highlights", "#ForYou"]
    for g in generic_pool:
        if len(tags) >= 5:
            break
        if g.lower() not in seen:
            seen.add(g.lower())
            tags.append(g)
    return tags[:5]


# ---------------------------------------------------------------------------
# Public temp host (Buffer's API needs a public media URL, no direct upload)
# ---------------------------------------------------------------------------
def upload_to_uguu(video_path):
    with open(video_path, "rb") as f:
        files = {"files[]": f}
        r = requests.post("https://uguu.se/upload", files=files, timeout=600)
    r.raise_for_status()
    data = r.json()
    return data["files"][0]["url"]


# ---------------------------------------------------------------------------
# Buffer: create post (GraphQL API)
# ---------------------------------------------------------------------------
class BufferSchemaError(RuntimeError):
    """Buffer GraphQL/schema-level error (bad field, bad enum, etc.) — this
    will fail identically for every candidate, so callers should stop
    immediately instead of burning downloads retrying the next video."""
    pass


def buffer_create_post(text, media_url=None, media_type=None):
    """media_type: None (text-only), "image", or "video"."""
    assets = []
    if media_type == "image" and media_url:
        assets = [{"image": {"url": media_url}}]
    elif media_type == "video" and media_url:
        assets = [{"video": {"url": media_url}}]

    # Facebook requires an explicit post type (POST, STORY, or REEL) via
    # metadata.facebook.type — without it Buffer rejects with "Facebook
    # posts require a type". Videos go as REEL (better organic reach than
    # a plain feed video); images go as a normal POST.
    # NOTE: Facebook Reels have strict constraints (duration <= 90s, min
    # resolution 540x960) that reject a large share of TikTok reposts.
    # Normal video posts don't have these limits, so everything posts as
    # "post" type — same behavior as the original direct-Graph-API version.
    fb_type = "post"

    query = """
    mutation CreatePost($input: CreatePostInput!) {
      createPost(input: $input) {
        ... on PostActionSuccess {
          post { id text dueAt }
        }
        ... on MutationError {
          message
        }
      }
    }
    """
    variables = {
        "input": {
            "text": text,
            "channelId": BUFFER_CHANNEL_ID,
            "schedulingType": "automatic",
            "mode": "addToQueue",
            "assets": assets,
            "metadata": {
                "facebook": {"type": fb_type}
            },
        }
    }
    r = requests.post(
        "https://api.buffer.com",
        json={"query": query, "variables": variables},
        headers={
            "Authorization": f"Bearer {BUFFER_API_KEY}",
            "Content-Type": "application/json",
        },
        timeout=60,
    )
    r.raise_for_status()
    data = r.json()
    if data.get("errors"):
        raise BufferSchemaError(f"Buffer GraphQL error: {data['errors']}")
    result = data["data"]["createPost"]
    if "message" in result:
        raise RuntimeError(f"Buffer rejected the post: {result['message']}")
    return result["post"]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Fetch/generate only, don't post")
    args = parser.parse_args()

    check_env()
    TMP_DIR.mkdir(exist_ok=True)

    state = load_state()
    n = len(TIKTOK_PROFILES)
    start_idx = state["current_profile_index"] % n

    profile = None
    candidates = []
    for step in range(n):
        idx = (start_idx + step) % n
        p = TIKTOK_PROFILES[idx]
        pstate = state["profiles"][p]
        print(f"Checking @{p} from cursor {pstate['cursor']} ({step + 1}/{n})")
        c, exhausted = find_candidates(p, pstate)

        if c:
            profile, candidates = p, c
            state["current_profile_index"] = idx
            print(f"  {len(c)} new video(s) found")
            break
        elif exhausted:
            print(f"  @{p} fully exhausted, resetting cursor, moving to next profile")
            pstate["cursor"] = 0
        else:
            print(f"  no new videos found in this run's page budget, will resume next run")

    save_state(state)

    if not candidates:
        print("\nNo postable video this run. Exiting.")
        return

    posted = False
    for v in candidates:
        vid, tt_caption = v["id"], v["caption"]
        video_path = TMP_DIR / f"{vid}.mp4"
        print(f"\nVideo {vid} (@{profile})")

        try:
            download_video(v["url"], video_path)

            print(f"Original TikTok caption: {tt_caption!r}")
            caption = generate_caption(tt_caption, GROQ_API_KEY)
            print(f"Caption: {caption}")

            if args.dry_run:
                print("Dry run, not posting.")
            else:
                print("Uploading video to public temp host...")
                public_url = upload_to_uguu(video_path)
                print("Creating Buffer post...")
                post = buffer_create_post(caption, media_url=public_url, media_type="video")
                print(f"Buffered post id: {post.get('id')} (queued via Buffer, will publish on schedule)")

            state["profiles"][profile]["posted_ids"].append(vid)
            save_state(state)
            posted = True

        except BufferSchemaError as e:
            print(f"Failed (Buffer schema/config error — same for every video, stopping run): {e}")
            if video_path.exists():
                video_path.unlink()
            break
        except Exception as e:
            print(f"Failed: {e}")
        finally:
            if video_path.exists():
                video_path.unlink()

        if posted:
            break

    if not posted:
        print("\nNo video posted this run (all candidates failed).")

    try:
        TMP_DIR.rmdir()
    except OSError:
        pass

    print("Done.")


if __name__ == "__main__":
    main()
