#!/usr/bin/env python3
"""
Page B video poster — TikTok repost from @epicweathermoments (Groq-rewritten
caption), posted to a Facebook Page via Buffer.

Each run does exactly ONE video post. Image-card posting has been removed —
this script only reposts video now.

CHANGE FROM PREVIOUS VERSION:
  - Merged into one file / one GitHub Action run per post.
  - No more direct Meta Graph API calls (no FB_SYSTEM_USER_TOKEN / page
    token exchange). Posting now goes through Buffer instead.
  - Instagram posting removed entirely — this Page isn't IG-linked, and
    Buffer treats FB/IG as separate channels anyway.
  - Image-card generation (Groq + Pollinations) removed entirely — video-only now.

ENV VARS (GitHub Actions secrets):
  BUFFER_API_KEY     - Buffer personal API key (Buffer > developer settings,
                        must be generated by an org owner)
  BUFFER_CHANNEL_ID  - the Buffer channel ID for this Page's Facebook connection
  GROQ_API_KEY       - Groq API key
  GROQ_MODEL         - optional, default "openai/gpt-oss-20b" (used for the
                        video-caption rewrite)
  MAX_VIDEOS         - optional, default 1
  STATE_FILE         - optional, default "state.json" (video dedupe/cursor)

REMOVED ENV VARS (no longer used, can delete these secrets):
  FB_SYSTEM_USER_TOKEN, FB_PAGE_ID, CARD_TYPE

TikTok profile is NOT a secret — edit TIKTOK_PROFILE below directly in code.

Usage:
  python page_b_combined.py --dry-run   # test without posting
  python page_b_combined.py             # live run (posts one video)
"""

import os
import sys
import io
import re
import json
import time
import math
import random
import argparse
import pathlib
import urllib.parse
import requests
import yt_dlp


# ---------------------------------------------------------------------------
# Shared config
# ---------------------------------------------------------------------------
BUFFER_API_KEY = os.environ.get("BUFFER_API_KEY", "")
BUFFER_CHANNEL_ID = os.environ.get("BUFFER_CHANNEL_ID", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")


BASE_DIR = os.path.dirname(os.path.abspath(__file__))

REQUIRED = {
    "BUFFER_API_KEY": BUFFER_API_KEY,
    "BUFFER_CHANNEL_ID": BUFFER_CHANNEL_ID,
    "GROQ_API_KEY": GROQ_API_KEY,
}


def check_env():
    missing = [k for k, v in REQUIRED.items() if not v]
    if missing:
        print(f"[FATAL] Missing env vars: {', '.join(missing)}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Buffer: create post (GraphQL API) — shared by both content types
# ---------------------------------------------------------------------------
class BufferSchemaError(RuntimeError):
    """Buffer GraphQL/schema-level error (bad field, bad enum, etc.) — this
    will fail identically for every candidate, so callers should stop
    immediately instead of burning downloads retrying the next video."""
    pass


def buffer_create_post(text, media_url=None, media_type=None):
    """media_type: None (text-only), "image", or "video"."""
    assets = []
    if media_type == "image" and media_url:
        assets = [{"image": {"url": media_url}}]
    elif media_type == "video" and media_url:
        assets = [{"video": {"url": media_url}}]

    # Facebook requires an explicit post type (POST, STORY, or REEL) via
    # metadata.facebook.type — without it Buffer rejects with "Facebook
    # posts require a type". Videos go as REEL (better organic reach than
    # a plain feed video); images go as a normal POST.
    # NOTE: Facebook Reels have strict constraints (duration <= 90s, min
    # resolution 540x960) that reject a large share of TikTok reposts.
    # Normal video posts don't have these limits, so everything posts as
    # "post" type — same behavior as the original direct-Graph-API version.
    fb_type = "post"

    query = """
    mutation CreatePost($input: CreatePostInput!) {
      createPost(input: $input) {
        ... on PostActionSuccess {
          post { id text dueAt }
        }
        ... on MutationError {
          message
        }
      }
    }
    """
    variables = {
        "input": {
            "text": text,
            "channelId": BUFFER_CHANNEL_ID,
            "schedulingType": "automatic",
            "mode": "shareNow",
            "assets": assets,
            "metadata": {
                "facebook": {"type": fb_type}
            },
        }
    }
    r = requests.post(
        "https://api.buffer.com",
        json={"query": query, "variables": variables},
        headers={
            "Authorization": f"Bearer {BUFFER_API_KEY}",
            "Content-Type": "application/json",
        },
        timeout=60,
    )
    r.raise_for_status()
    data = r.json()
    if data.get("errors"):
        raise BufferSchemaError(f"Buffer GraphQL error: {data['errors']}")
    result = data["data"]["createPost"]
    if "message" in result:
        raise RuntimeError(f"Buffer rejected the post: {result['message']}")
    return result["post"]


def upload_to_uguu(file_path):
    """Public temp host — Buffer's API needs a public media URL for both
    images and videos, it does not accept direct file uploads."""
    with open(file_path, "rb") as f:
        files = {"files[]": f}
        r = requests.post("https://uguu.se/upload", files=files, timeout=600)
    r.raise_for_status()
    data = r.json()
    return data["files"][0]["url"]



# ===========================================================================
# TYPE "video" — TikTok repost from @naturevibes689
# ===========================================================================

TIKTOK_PROFILE = "epicweathermoments"
VIDEO_GROQ_MODEL = os.environ.get("GROQ_MODEL", "openai/gpt-oss-20b")
DEDUPE_DIR = pathlib.Path(os.environ.get("DEDUPE_DIR", "dedupe"))
VIDEO_STATE_FILE = DEDUPE_DIR / os.environ.get("STATE_FILE", "state.json")
TMP_DIR = pathlib.Path("tmp_videos")
PAGE_SIZE = 5
MAX_PAGES_PER_RUN = 5


def _ydl_opts(**extra):
    opts = {
        "quiet": True,
        "no_warnings": True,
        "skip_download": True,
        "http_headers": {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            )
        },
    }
    opts.update(extra)
    return opts


def load_video_state():
    DEDUPE_DIR.mkdir(parents=True, exist_ok=True)
    if VIDEO_STATE_FILE.exists():
        with open(VIDEO_STATE_FILE, "r", encoding="utf-8") as f:
            state = json.load(f)
    else:
        state = {}
    state.setdefault("cursor", 0)
    state.setdefault("posted_ids", [])
    return state


def save_video_state(state):
    DEDUPE_DIR.mkdir(parents=True, exist_ok=True)
    with open(VIDEO_STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)


def list_profile_videos(profile):
    url = f"https://www.tiktok.com/@{profile}"
    with yt_dlp.YoutubeDL(_ydl_opts(extract_flat=True)) as ydl:
        info = ydl.extract_info(url, download=False)
    entries = info.get("entries") or []
    videos = []
    for e in entries:
        vid = e.get("id")
        if not vid:
            continue
        videos.append({
            "id": vid,
            "url": e.get("url") or e.get("webpage_url") or f"https://www.tiktok.com/@{profile}/video/{vid}",
        })
    return videos


def fetch_video_meta(video_url):
    with yt_dlp.YoutubeDL(_ydl_opts()) as ydl:
        info = ydl.extract_info(video_url, download=False)
    caption = (info.get("description") or info.get("title") or "").strip()
    return {"caption": caption}


def find_candidates(profile, vstate):
    all_videos = list_profile_videos(profile)
    if not all_videos:
        return [], True

    total = len(all_videos)
    cursor = vstate["cursor"]
    posted = set(vstate["posted_ids"])

    for _ in range(MAX_PAGES_PER_RUN):
        if cursor >= total:
            vstate["cursor"] = cursor
            return [], True

        page = all_videos[cursor:cursor + PAGE_SIZE]
        unposted = [v for v in page if v["id"] not in posted]

        if unposted:
            vstate["cursor"] = cursor
            candidates = []
            for v in unposted:
                meta = fetch_video_meta(v["url"])
                candidates.append({"id": v["id"], "caption": meta["caption"], "url": v["url"]})
            return candidates, False

        cursor += len(page)
        vstate["cursor"] = cursor
        if cursor >= total:
            return [], True

    return [], False


def download_video(video_url, dest_path):
    opts = _ydl_opts(
        skip_download=False,
        outtmpl=str(dest_path),
        format="bestvideo*+bestaudio/best",
        format_sort=["res", "fps", "br"],
        merge_output_format="mp4",
    )
    with yt_dlp.YoutubeDL(opts) as ydl:
        ydl.download([video_url])
    return dest_path


# Fallback captions — used ONLY when the original TikTok caption has no
# usable text AND no hashtags (nothing for Groq to work with at all).
VIDEO_FALLBACK_CAPTIONS = [
    "Nature never stops putting on a show.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #MustWatch",
    "Some views make you forget everything else.\n\n#NatureVibes #EarthPix #WildEarth #NaturePhotography #MustWatch",
    "This is the planet doing what it does best.\n\n#NatureLovers #WildEarth #EarthPix #NatureVibes #Breathtaking",
    "Untouched, wild, and absolutely stunning.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #MustWatch",
    "Moments like this remind you how wild the world is.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #Untamed",
    "The wild doesn't need a filter.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #Breathtaking",
    "Earth really outdid itself with this one.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #MustWatch",
    "Pure, raw, untamed nature.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #Untamed",
    "Some sights are worth stopping for.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #Breathtaking",
    "This is what wild really looks like.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #MustWatch",
]


def pick_video_fallback_caption():
    return random.choice(VIDEO_FALLBACK_CAPTIONS)


def generate_video_caption(original_caption, groq_key, model=VIDEO_GROQ_MODEL, max_words=15, max_attempts=3):
    original_caption = (original_caption or "").strip()

    # yt-dlp falls back to a placeholder title "TikTok video #<video_id>" when
    # a video has no real title/description. Strip that out first, otherwise
    # the video-id gets mistaken for a real hashtag below.
    original_caption = re.sub(r"(?i)^tiktok video\s*#?\d*$", "", original_caption).strip()

    hashtags_found = re.findall(r"#\w+", original_caption)
    # Drop purely-numeric hashtags (e.g. "#7663508317964094751") — these are
    # video-id artifacts, never a real topic tag.
    hashtags_found = [h for h in hashtags_found if not h[1:].isdigit()]

    text_only = re.sub(r"#\w+", "", original_caption).strip()
    text_only = re.sub(r"\s{2,}", " ", text_only)

    if not text_only and not hashtags_found:
        print("[INFO] No usable text or hashtags in source caption — using fallback caption.")
        return pick_video_fallback_caption()

    if not text_only and hashtags_found:
        source_block = (
            "The original caption had NO descriptive sentence — only these "
            "hashtags: " + " ".join(hashtags_found) + "\n"
            "Use these hashtags ONLY as a clue to figure out the video's topic/theme, "
            "then write a natural caption about that theme. Do not mention that "
            "hashtags were your source."
        )
    else:
        source_block = f"ORIGINAL CAPTION:\n{original_caption}"

    base_prompt = (
        "You are a social media caption writer. You will be given the ORIGINAL "
        "caption from a TikTok video (any topic/niche — news, devotional, motivation, "
        "comedy, film clip, etc). Rewrite it for Facebook/Instagram in the SAME "
        "language/tone as the original (if it's Hindi/Hinglish, reply in Hindi/Hinglish; "
        "if English, reply in English). Output in this EXACT format:\n\n"
        "<one punchy caption sentence>\n"
        "\n"
        "#hashtag1\n#hashtag2\n#hashtag3\n#hashtag4\n#hashtag5\n\n"
        "Strict rules:\n"
        f"- Line 1 is ONE sentence, MAXIMUM {max_words} words (count carefully — "
        "9 or 10 words is ideal, never go over the limit).\n"
        "- No emojis, no digits/numbers, in line 1.\n"
        "- Do NOT invent facts not present in the original caption.\n"
        "- Do NOT mention TikTok, any username/handle, video ID, or any TikTok-related "
        "word anywhere — the sentence must read naturally with no gaps or leftover "
        "words if such a mention were ever removed.\n"
        "- Then a blank line, then EXACTLY 5 hashtags, one per line.\n"
        "- Hashtags must be SEO-relevant to the actual content/niche of this video "
        "(not generic filler like #viral #trending #fyp) — think what someone would "
        "actually search to find this content. No spaces, no numbers, no repeats, "
        "no # symbol duplicated.\n"
        "- Output ONLY the caption + hashtags, nothing else (no preamble, no quotes, "
        "no explanation).\n\n"
        f"{source_block}"
    )

    prompt = base_prompt
    body_raw, hashtag_lines = "", []

    for attempt in range(1, max_attempts + 1):
        r = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {groq_key}"},
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.7,
                "max_tokens": 150,
                "reasoning_effort": "low",
                "reasoning_format": "hidden",
            },
            timeout=30,
        )
        r.raise_for_status()
        raw = r.json()["choices"][0]["message"]["content"].strip()
        body_raw, hashtag_lines = split_caption(raw)

        if has_forbidden_terms(body_raw):
            prompt = (
                base_prompt
                + "\n\nYour previous attempt mentioned TikTok, a video ID, a handle, "
                  "or a number in line 1. Rewrite line 1 from scratch as a natural "
                  "sentence with NO such mentions and no leftover gaps."
            )
            continue

        body = clean_body(body_raw)
        if body and len(body.split()) <= max_words:
            break

        prompt = (
            base_prompt
            + f"\n\nYour previous attempt was too long. Rewrite line 1 to be "
              f"{max_words} words or fewer, same meaning, same format."
        )
    else:
        body = clean_body(body_raw)
        words = body.split()
        if len(words) > max_words:
            words = words[:max_words]
        body = tidy_dangling(" ".join(words))

    hashtags = clean_hashtags(hashtag_lines)
    if not hashtags:
        hashtags = fallback_hashtags(original_caption)

    return f"{body}\n\n" + "\n".join(hashtags)


def has_forbidden_terms(text):
    if re.search(r"(?i)\btik\s?tok\b", text):
        return True
    if re.search(r"(?i)\b(video|clip|post|reel)?\s*id\b", text):
        return True
    if re.search(r"@\w+", text):
        return True
    if re.search(r"\d", text):
        return True
    return False


def split_caption(raw):
    lines = [l.strip() for l in raw.splitlines() if l.strip()]
    body_lines, hashtag_lines = [], []
    for l in lines:
        if l.startswith("#"):
            hashtag_lines.append(l)
        else:
            body_lines.append(l)
    return " ".join(body_lines).strip(), hashtag_lines


def clean_body(body_raw):
    text = re.sub(r"(?i)\btik\s?tok\b", "", body_raw)
    text = re.sub(r"(?i)\b(video|clip|post|reel)?\s*id\b", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\s+([.,!?])", r"\1", text).strip()

    match = re.search(r"[^.!?]+[.!?]?", text)
    if match:
        text = match.group(0).strip()
    return text


def tidy_dangling(text):
    edge_words = {"by", "from", "on", "in", "at", "with", "to", "of", "the",
                  "a", "an", "and", "or", "this", "that", "for"}
    words = text.split()
    while words and words[-1].strip(".,!?").lower() in edge_words:
        words.pop()
    while words and words[0].lower() in edge_words:
        words.pop(0)
    text = " ".join(words).strip()
    if text:
        text = text[0].upper() + text[1:]
        if text[-1] not in ".!?":
            text += "."
    return text


def clean_hashtags(hashtag_lines):
    hashtags = []
    for l in hashtag_lines:
        hashtags.extend(re.findall(r"#\w+", l))

    seen, clean_tags = set(), []
    for h in hashtags:
        h = re.sub(r"[^A-Za-z#]", "", h)
        if len(h) > 1 and h.lower() not in seen:
            seen.add(h.lower())
            clean_tags.append(h)
    return clean_tags[:5]


def fallback_hashtags(original_caption):
    words = re.findall(r"[A-Za-z]{4,}", original_caption or "")
    stop = {"this", "that", "with", "from", "your", "have", "will", "just",
            "what", "when", "they", "them", "video", "watch", "tiktok"}
    seen, tags = set(), []
    for w in words:
        wl = w.lower()
        if wl in stop or wl in seen:
            continue
        seen.add(wl)
        tags.append("#" + w.capitalize())
        if len(tags) == 5:
            break
    generic_pool = ["#Explore", "#DailyDose", "#MustWatch", "#Highlights", "#ForYou"]
    for g in generic_pool:
        if len(tags) >= 5:
            break
        if g.lower() not in seen:
            seen.add(g.lower())
            tags.append(g)
    return tags[:5]


def run_video_post(dry_run: bool) -> bool:
    TMP_DIR.mkdir(exist_ok=True)
    vstate = load_video_state()
    print(f"Checking @{TIKTOK_PROFILE} from cursor {vstate['cursor']}")
    candidates, exhausted = find_candidates(TIKTOK_PROFILE, vstate)

    if exhausted and not candidates:
        print(f"  @{TIKTOK_PROFILE} fully exhausted, resetting cursor")
        vstate["cursor"] = 0
    save_video_state(vstate)

    if not candidates:
        print("No postable video this run.")
        return False

    posted = False
    for v in candidates:
        vid, tt_caption = v["id"], v["caption"]
        video_path = TMP_DIR / f"{vid}.mp4"
        print(f"\nVideo {vid} (@{TIKTOK_PROFILE})")

        try:
            download_video(v["url"], video_path)
            print(f"Original TikTok caption: {tt_caption!r}")
            caption = generate_video_caption(tt_caption, GROQ_API_KEY)
            print(f"Caption: {caption}")

            if dry_run:
                print("Dry run, not posting.")
            else:
                print("Uploading video to public temp host...")
                public_url = upload_to_uguu(video_path)
                print("Creating Buffer post...")
                post = buffer_create_post(caption, media_url=public_url, media_type="video")
                print(f"Buffered post id: {post.get('id')} (queued via Buffer, will publish on schedule)")

            vstate["posted_ids"].append(vid)
            save_video_state(vstate)
            posted = True

        except BufferSchemaError as e:
            print(f"Failed (Buffer schema/config error — same for every video, stopping run): {e}")
            if video_path.exists():
                video_path.unlink()
            break
        except Exception as e:
            print(f"Failed: {e}")
        finally:
            if video_path.exists():
                video_path.unlink()

        if posted:
            break

    try:
        TMP_DIR.rmdir()
    except OSError:
        pass

    return posted


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Fetch/generate only, don't post")
    args = parser.parse_args()

    check_env()

    ok = run_video_post(args.dry_run)

    print("Done." if ok else "Nothing posted this run.")


if __name__ == "__main__":
    main()
