#!/usr/bin/env python3
"""
Page B combined poster — alternates between two content types on the same
Facebook Page, posting via Buffer:

  TYPE "image": an original AI-generated Travel/Nature engagement card
                (Groq for text + Pollinations.ai for the photo) — this is
                NOT a repost, it's freshly generated content.
  TYPE "video": a TikTok repost from @naturevibes689 (Groq-rewritten caption).

Each run does exactly ONE post, alternating type every run (state kept in
state/post_type.json), so the page gets a healthy original-content /
repost mix instead of running two separate scripts back to back.

CHANGE FROM PREVIOUS VERSION (2 separate scripts):
  - Merged into one file / one GitHub Action run per post.
  - No more direct Meta Graph API calls (no FB_SYSTEM_USER_TOKEN / page
    token exchange). Posting now goes through Buffer instead.
  - Instagram posting removed entirely — this Page isn't IG-linked, and
    Buffer treats FB/IG as separate channels anyway.

ENV VARS (GitHub Actions secrets):
  BUFFER_API_KEY     - Buffer personal API key (Buffer > developer settings,
                        must be generated by an org owner)
  BUFFER_CHANNEL_ID  - the Buffer channel ID for this Page's Facebook connection
  GROQ_API_KEY       - Groq API key
  GROQ_MODEL         - optional, default "llama-3.3-70b-versatile" (used for
                        the video-caption rewrite; the image-card generator
                        uses its own model, see IMAGE_GROQ_MODEL below)
  MAX_VIDEOS         - optional, default 1
  STATE_FILE         - optional, default "state.json" (video dedupe/cursor)
  CARD_TYPE          - optional — force a specific card type instead of rotation

REMOVED ENV VARS (no longer used, can delete these secrets):
  FB_SYSTEM_USER_TOKEN, FB_PAGE_ID

TikTok profile is NOT a secret — edit TIKTOK_PROFILE below directly in code.

Usage:
  python page_b_combined.py --dry-run   # test without posting
  python page_b_combined.py             # live run (posts ONE item: image or video)
  python page_b_combined.py --force-type image   # skip alternation, force this run's type
  python page_b_combined.py --force-type video
"""

import os
import sys
import io
import re
import json
import time
import math
import random
import argparse
import pathlib
import urllib.parse
import requests
import yt_dlp
from PIL import Image, ImageDraw, ImageFont, ImageFilter

# ---------------------------------------------------------------------------
# Shared config
# ---------------------------------------------------------------------------
BUFFER_API_KEY = os.environ.get("BUFFER_API_KEY", "")
BUFFER_CHANNEL_ID = os.environ.get("BUFFER_CHANNEL_ID", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATE_DIR = pathlib.Path(os.path.join(BASE_DIR, "state"))
POST_TYPE_STATE_FILE = STATE_DIR / "post_type.json"

REQUIRED = {
    "BUFFER_API_KEY": BUFFER_API_KEY,
    "BUFFER_CHANNEL_ID": BUFFER_CHANNEL_ID,
    "GROQ_API_KEY": GROQ_API_KEY,
}


def check_env():
    missing = [k for k, v in REQUIRED.items() if not v]
    if missing:
        print(f"[FATAL] Missing env vars: {', '.join(missing)}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Buffer: create post (GraphQL API) — shared by both content types
# ---------------------------------------------------------------------------
def buffer_create_post(text, media_url=None, media_type=None):
    """media_type: None (text-only), "image", or "video"."""
    assets = []
    if media_type == "image" and media_url:
        assets = [{"image": {"url": media_url}}]
    elif media_type == "video" and media_url:
        assets = [{"video": {"url": media_url}}]

    # Facebook requires an explicit post type (POST, STORY, or REEL) via
    # metadata.facebook.type — without it Buffer rejects with "Facebook
    # posts require a type". Videos go as REEL (better organic reach than
    # a plain feed video); images go as a normal POST.
    fb_type = "REEL" if media_type == "video" else "POST"

    query = """
    mutation CreatePost($input: CreatePostInput!) {
      createPost(input: $input) {
        ... on PostActionSuccess {
          post { id text dueAt }
        }
        ... on MutationError {
          message
        }
      }
    }
    """
    variables = {
        "input": {
            "text": text,
            "channelId": BUFFER_CHANNEL_ID,
            "schedulingType": "automatic",
            "mode": "addToQueue",
            "assets": assets,
            "metadata": {
                "facebook": {"type": fb_type}
            },
        }
    }
    r = requests.post(
        "https://api.buffer.com",
        json={"query": query, "variables": variables},
        headers={
            "Authorization": f"Bearer {BUFFER_API_KEY}",
            "Content-Type": "application/json",
        },
        timeout=60,
    )
    r.raise_for_status()
    data = r.json()
    if data.get("errors"):
        raise RuntimeError(f"Buffer GraphQL error: {data['errors']}")
    result = data["data"]["createPost"]
    if "message" in result:
        raise RuntimeError(f"Buffer rejected the post: {result['message']}")
    return result["post"]


def upload_to_uguu(file_path):
    """Public temp host — Buffer's API needs a public media URL for both
    images and videos, it does not accept direct file uploads."""
    with open(file_path, "rb") as f:
        files = {"files[]": f}
        r = requests.post("https://uguu.se/upload", files=files, timeout=600)
    r.raise_for_status()
    data = r.json()
    return data["files"][0]["url"]


# ===========================================================================
# TYPE "image" — AI-generated Travel/Nature engagement card
# ===========================================================================

IMAGE_GROQ_MODEL = "openai/gpt-oss-120b"  # llama-3.3-70b-versatile is deprecated (shuts down 08/16/26)

POLLINATIONS_BASE = "https://image.pollinations.ai/prompt"
POLLINATIONS_MODEL = "flux"
POLLINATIONS_TIMEOUT = 90
POLLINATIONS_RETRIES = 2

IMAGE_STYLE_SUFFIX = (
    ", moody cinematic color grading, deep rich saturated tones, slightly "
    "darker exposure, dusk-like atmospheric lighting, high contrast — not "
    "pitch black, details still visible"
)

FONTS_DIR = os.path.join(BASE_DIR, "fonts")
CARD_STATE_FILE = os.path.join(BASE_DIR, "state", "last_card.json")
OUTPUT_IMAGE = os.path.join(BASE_DIR, "post_output.jpg")

os.makedirs(FONTS_DIR, exist_ok=True)

IMG_SIZE = 1080

FONT_SOURCES = {
    "PTSerif-Bold.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/ptserif/PT_Serif-Web-Bold.ttf",
    "PTSerif-Regular.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/ptserif/PT_Serif-Web-Regular.ttf",
    "Poppins-Bold.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/poppins/Poppins-Bold.ttf",
    "Poppins-SemiBold.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/poppins/Poppins-SemiBold.ttf",
    "Poppins-Regular.ttf": "https://raw.githubusercontent.com/google/fonts/main/ofl/poppins/Poppins-Regular.ttf",
}


def ensure_fonts():
    for filename, url in FONT_SOURCES.items():
        path = os.path.join(FONTS_DIR, filename)
        if not os.path.exists(path):
            try:
                resp = requests.get(url, timeout=30)
                resp.raise_for_status()
                with open(path, "wb") as f:
                    f.write(resp.content)
            except Exception as e:
                print(f"[WARN] Could not download font {filename}: {e}")


def font(name, size):
    path = os.path.join(FONTS_DIR, name)
    if os.path.exists(path):
        return ImageFont.truetype(path, size)
    return ImageFont.load_default()


CARD_TYPES = {
    "guess_the_place": {
        "label": "Guess The Place", "emoji": "🧭",
        "gradient": ((30, 144, 255), (0, 60, 90)), "text_color": (255, 255, 255),
        "accent": (255, 214, 0), "quote_font": "Poppins-Bold.ttf", "decoration": "compass",
        "cta": "Guess the place in comments! 👇🌍", "cta_plain": "GUESS THE PLACE IN COMMENTS",
        "use_angle": True,
        "instruction": (
            "Give 2 to 3 vivid, SPECIFIC clues about ONE real, well-known "
            "natural or travel destination on Earth — WITHOUT naming it "
            "directly. Each clue must be a concrete, checkable fact (an "
            "exact geographic feature, a specific natural phenomenon, a "
            "climate/altitude detail, a cultural or historical detail) — "
            "NOT vague filler like 'a beautiful place' or 'amazing views'. "
            "Guessable but not too easy."
        ),
        "max_chars": 150,
    },
    "would_you_rather": {
        "label": "Would You Rather", "emoji": "⚡",
        "gradient": ((255, 126, 95), (255, 94, 177)), "text_color": (255, 255, 255),
        "accent": (255, 255, 255), "quote_font": "Poppins-Bold.ttf", "decoration": "lightning_split",
        "cta": "Comment A or B 👇", "cta_plain": "COMMENT A OR B", "use_angle": False,
        "instruction": (
            "Write a fun 'Would you rather' travel dilemma with two "
            "SPECIFIC, vivid, contrasting travel or nature experiences "
            "(not generic categories like 'mountains vs beach' — instead "
            "pick concrete experiences, e.g. 'sleeping in an ice hotel' vs "
            "'camping under the Sahara stars'). Format exactly like: "
            "'OPTION A  or  OPTION B' — each side only 3-6 words, plain "
            "text, NO emojis. Be creative and avoid repeating obvious pairs."
        ),
        "max_chars": 90,
    },
    "true_or_false": {
        "label": "True or False", "emoji": "❓",
        "gradient": ((46, 125, 50), (10, 40, 20)), "text_color": (255, 255, 255),
        "accent": (255, 255, 255), "quote_font": "PTSerif-Bold.ttf", "decoration": "check_cross",
        "cta": "TRUE or FALSE? Comment below 👇", "cta_plain": "TRUE OR FALSE? COMMENT BELOW",
        "use_angle": False,
        "instruction": (
            "Write one surprising, real, fact-checkable TRUE or FALSE "
            "statement about nature, geography, wildlife, or a famous "
            "travel destination on Earth. It MUST include a specific, "
            "concrete detail (a number, measurement, named place, or named "
            "phenomenon) — NOT a vague generalization. Under 110 "
            "characters. Do not reveal whether it is true or false."
        ),
        "max_chars": 110,
    },
    "bucket_list_poll": {
        "label": "Bucket List Check", "emoji": "📍",
        "gradient": ((222, 184, 135), (101, 67, 33)), "text_color": (255, 255, 255),
        "accent": (255, 255, 255), "quote_font": "Poppins-Bold.ttf", "decoration": "map_pins",
        "cta": "Been here? ✅  Bucket list? 📝 Comment!", "cta_plain": "BEEN HERE OR BUCKET LIST? COMMENT!",
        "use_angle": True,
        "instruction": (
            "Describe ONE breathtaking real natural wonder or travel "
            "destination on Earth in one vivid, enticing sentence. Include "
            "at least one SPECIFIC concrete detail (exact feature, color, "
            "size, or unusual fact) — NOT generic filler like 'a beautiful "
            "place' or 'stunning views'. Make people want to say whether "
            "they've been there or want to go."
        ),
        "max_chars": 130,
    },
    "caption_this": {
        "label": "Caption This View", "emoji": "📸",
        "gradient": ((186, 220, 255), (80, 120, 200)), "text_color": (255, 255, 255),
        "accent": (255, 255, 255), "quote_font": "PTSerif-Bold.ttf", "decoration": "camera_corners",
        "cta": "Caption this in ONE word 👇", "cta_plain": "CAPTION THIS IN ONE WORD", "use_angle": True,
        "instruction": (
            "Vividly describe, in one evocative sentence, a stunning REAL "
            "nature or travel scene (sunrise over a named mountain range, "
            "a specific type of waterfall, a particular desert, northern "
            "lights, etc.) with at least one SPECIFIC sensory or visual "
            "detail — NOT vague filler like 'a beautiful view'. Write it "
            "as if setting the scene for a photo, inviting people to "
            "caption it."
        ),
        "max_chars": 130,
    },
}

CAPTION_ANGLES = [
    "a bold, punchy declarative line",
    "a short, dreamy, evocative line",
    "a warm, conversational line as if talking to a fellow traveler",
    "a sharp, curiosity-sparking line",
]

TAGS_BY_TYPE = {
    "guess_the_place": "#travel #guessthelocation #wanderlust #earthpix",
    "would_you_rather": "#travel #wouldyourather #traveltok #naturelovers",
    "true_or_false": "#travelfacts #naturefacts #didyouknow #geography",
    "bucket_list_poll": "#bucketlist #travelgoals #wanderlust #explore",
    "caption_this": "#captionthis #naturephotography #travelphotography #earth",
}

FALLBACK_CONTENT = {
    "guess_the_place": "A frozen kingdom of fire and ice, where glaciers meet volcanoes and the sky dances in green.",
    "would_you_rather": "Misty mountains  or  golden beaches",
    "true_or_false": "The Sahara Desert was once covered in lakes and grassland.",
    "bucket_list_poll": "A hidden turquoise lagoon ringed by cliffs, reachable only by a narrow jungle trail.",
    "caption_this": "Golden light spilling over endless sand dunes as the last camel train disappears into the horizon.",
}

FALLBACK_IMAGE_PROMPTS = {
    "guess_the_place": "cinematic aerial photo of iceland glacier lagoon with volcanic mountains, dramatic golden light, travel photography",
    "would_you_rather": "cinematic split scene misty green mountains and golden tropical beach, travel photography, wide shot",
    "true_or_false": "vast sahara desert sand dunes at golden hour, cinematic wide shot, travel photography",
    "bucket_list_poll": "hidden turquoise lagoon surrounded by jungle cliffs, aerial cinematic travel photography",
    "caption_this": "golden sand dunes desert sunset with camel silhouette, cinematic wide shot, travel photography",
}


def generate_content(card_key: str) -> tuple:
    card = CARD_TYPES[card_key]

    if not GROQ_API_KEY:
        print("[INFO] GROQ_API_KEY not set — using fallback sample content.")
        return FALLBACK_CONTENT[card_key], FALLBACK_IMAGE_PROMPTS[card_key]

    angle_part = ""
    if card["use_angle"]:
        angle = random.choice(CAPTION_ANGLES)
        angle_part = f"\nStyle: {angle}."

    prompt = (
        f"You are writing a highly engaging Facebook image-card for a "
        f"travel & nature page.\n\n"
        f"{card['instruction']}{angle_part}\n\n"
        f"Also write a short photographic scene description (for an AI image "
        f"generator) that visually matches this content — real Earth nature "
        f"or travel scenery, cinematic travel-photography style, no text, no "
        f"logos, no watermarks, no close-up human faces. Under 22 words.\n\n"
        f"Respond with ONLY valid JSON, nothing else, no markdown fences, in "
        f'exactly this format: {{"text": "...", "image_prompt": "..."}}\n\n'
        f"Rules for 'text': English, under {card['max_chars']} characters, "
        f"no hashtags, no emojis, no quotation marks, no explanation — just "
        f"the line itself. Must be about a REAL place/nature/geography, "
        f"never fictional. Do not reveal a true/false answer. Avoid vague, "
        f"generic filler phrases (e.g. 'a beautiful place', 'amazing "
        f"views', 'stunning scenery') — every line must contain at least "
        f"one specific, concrete, information-rich detail."
    )

    try:
        resp = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"},
            json={
                "model": IMAGE_GROQ_MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 1.0,
                "max_tokens": 220,
            },
            timeout=30,
        )
        resp.raise_for_status()
        raw = resp.json()["choices"][0]["message"]["content"].strip()
        raw = raw.strip("`")
        if raw.lower().startswith("json"):
            raw = raw[4:].strip()

        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            raw = match.group(0)

        data = json.loads(raw)

        text = str(data.get("text", "")).strip().strip('"').strip("'").strip()
        image_prompt = str(data.get("image_prompt", "")).strip()

        max_len = card["max_chars"] + 40
        if len(text) > max_len:
            text = text[:max_len].rsplit(" ", 1)[0] + "..."

        if not text:
            text = FALLBACK_CONTENT[card_key]
        if not image_prompt:
            image_prompt = FALLBACK_IMAGE_PROMPTS[card_key]

        return text, image_prompt
    except Exception as e:
        print(f"[WARN] Groq content generation failed ({e}), using fallback.")
        return FALLBACK_CONTENT[card_key], FALLBACK_IMAGE_PROMPTS[card_key]


def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def draw_gradient(size, top_color, bottom_color, diagonal=True):
    img = Image.new("RGB", (size, size), top_color)
    draw = ImageDraw.Draw(img)
    if diagonal:
        for y in range(size):
            t = y / size
            row_color = lerp(top_color, bottom_color, t)
            draw.line([(0, y), (size, y)], fill=row_color)
        overlay = Image.new("L", (size, size), 0)
        odraw = ImageDraw.Draw(overlay)
        for x in range(size):
            odraw.line([(x, 0), (0, x)], fill=int(30 * (x / size)))
        dark = Image.new("RGB", (size, size), (0, 0, 0))
        img = Image.composite(dark, img, overlay.point(lambda p: int(p * 0.5)))
    else:
        for y in range(size):
            t = y / size
            draw.line([(0, y), (size, y)], fill=lerp(top_color, bottom_color, t))
    return img


def build_gradient_background(card: dict) -> Image.Image:
    top_c, bottom_c = card["gradient"]
    img = draw_gradient(IMG_SIZE, top_c, bottom_c, diagonal=True)

    vignette = Image.new("L", (IMG_SIZE, IMG_SIZE), 0)
    vdraw = ImageDraw.Draw(vignette)
    vdraw.ellipse([-200, -200, IMG_SIZE + 200, IMG_SIZE + 200], fill=255)
    vignette = vignette.filter(ImageFilter.GaussianBlur(180))
    dark_layer = Image.new("RGB", (IMG_SIZE, IMG_SIZE), (0, 0, 0))
    img = Image.composite(img, dark_layer, vignette)
    return img


def crop_to_square(img: Image.Image, size: int) -> Image.Image:
    img = img.convert("RGB")
    w, h = img.size
    scale = size / min(w, h)
    new_w, new_h = int(w * scale) + 1, int(h * scale) + 1
    img = img.resize((new_w, new_h))
    left = (new_w - size) // 2
    top = (new_h - size) // 2
    return img.crop((left, top, left + size, top + size))


def apply_photo_overlay(img: Image.Image) -> Image.Image:
    img = img.convert("RGB")
    overlay = Image.new("L", (IMG_SIZE, IMG_SIZE), 85)
    odraw = ImageDraw.Draw(overlay)

    top_band = 360
    for y in range(top_band):
        alpha = int(190 * (1 - y / top_band))
        odraw.line([(0, y), (IMG_SIZE, y)], fill=max(alpha, 60))

    bottom_band = 380
    start_y = IMG_SIZE - bottom_band
    for y in range(start_y, IMG_SIZE):
        t = (y - start_y) / bottom_band
        alpha = int(200 * t)
        odraw.line([(0, y), (IMG_SIZE, y)], fill=max(alpha, 60))

    black = Image.new("RGB", (IMG_SIZE, IMG_SIZE), (0, 0, 0))
    return Image.composite(black, img, overlay)


def fetch_background_photo(image_prompt: str):
    prompt_enc = urllib.parse.quote(image_prompt + IMAGE_STYLE_SUFFIX)
    url = f"{POLLINATIONS_BASE}/{prompt_enc}"

    for attempt in range(1, POLLINATIONS_RETRIES + 1):
        try:
            seed = random.randint(1, 999999)
            resp = requests.get(
                url,
                params={"width": IMG_SIZE, "height": IMG_SIZE, "nologo": "true",
                        "seed": seed, "model": POLLINATIONS_MODEL},
                timeout=POLLINATIONS_TIMEOUT,
            )
            resp.raise_for_status()
            img = Image.open(io.BytesIO(resp.content))
            return crop_to_square(img, IMG_SIZE)
        except Exception as e:
            print(f"[WARN] Pollinations attempt {attempt}/{POLLINATIONS_RETRIES} failed: {e}")
            time.sleep(3)

    print("[WARN] Pollinations image fetch failed — falling back to gradient background.")
    return None


def wrap_text(draw, text, fnt, max_width):
    words = text.split()
    lines, current = [], ""
    for word in words:
        trial = f"{current} {word}".strip()
        bbox = draw.textbbox((0, 0), trial, font=fnt)
        if bbox[2] - bbox[0] <= max_width or not current:
            current = trial
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def draw_centered_multiline(draw, lines, fnt, center_x, center_y, fill, line_spacing=1.35, shadow=True):
    bboxes = [draw.textbbox((0, 0), line, font=fnt) for line in lines]
    heights = [b[3] - b[1] for b in bboxes]
    line_height = max(heights) * line_spacing
    total_height = line_height * len(lines)
    y = center_y - total_height / 2
    for line, bbox in zip(lines, bboxes):
        w = bbox[2] - bbox[0]
        x = center_x - w / 2
        if shadow:
            draw.text((x + 2, y + 3), line, font=fnt, fill=(0, 0, 0))
        draw.text((x, y), line, font=fnt, fill=fill)
        y += line_height
    return y


def draw_centered_single(draw, text, fnt, center_x, y, fill, shadow=True):
    bbox = draw.textbbox((0, 0), text, font=fnt)
    w = bbox[2] - bbox[0]
    x = center_x - w / 2
    if shadow:
        draw.text((x + 1, y + 2), text, font=fnt, fill=(0, 0, 0))
    draw.text((x, y), text, font=fnt, fill=fill)


def deco_compass(draw, accent):
    cx, cy = IMG_SIZE // 2, 150
    r = 46
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=accent, width=3)
    for ang in (0, 90, 180, 270):
        rad = math.radians(ang - 90)
        x2 = cx + (r + 16) * math.cos(rad)
        y2 = cy + (r + 16) * math.sin(rad)
        draw.line([(cx, cy), (x2, y2)], fill=accent, width=3)
    draw.polygon([(cx, cy - r + 8), (cx - 9, cy), (cx, cy + r - 8), (cx + 9, cy)], fill=accent)
    for cx2, cy2 in [(90, 90), (IMG_SIZE - 90, 90)]:
        draw.ellipse([cx2 - 6, cy2 - 6, cx2 + 6, cy2 + 6], fill=accent)


def deco_lightning_split(draw, accent):
    def bolt(cx, cy, s):
        pts = [(cx, cy - s), (cx - s * 0.5, cy + s * 0.15), (cx, cy + s * 0.15),
               (cx - s * 0.2, cy + s), (cx + s * 0.5, cy - s * 0.15), (cx, cy - s * 0.15)]
        draw.polygon(pts, fill=accent)

    bolt(150, 150, 34)
    bolt(IMG_SIZE - 150, 150, 34)
    cx, cy = IMG_SIZE // 2, 150
    draw.ellipse([cx - 34, cy - 34, cx + 34, cy + 34], outline=accent, width=3)
    vs_font = font("Poppins-Bold.ttf", 26)
    draw_centered_single(draw, "VS", vs_font, cx, cy - 16, accent, shadow=False)


def deco_check_cross(draw, accent):
    cx, cy, r = 130, 150, 40
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=accent, width=3)
    draw.line([(cx - 18, cy), (cx - 4, cy + 16), (cx + 20, cy - 16)], fill=accent, width=6)

    cx2 = IMG_SIZE - 130
    draw.ellipse([cx2 - r, cy - r, cx2 + r, cy + r], outline=accent, width=3)
    draw.line([(cx2 - 16, cy - 16), (cx2 + 16, cy + 16)], fill=accent, width=6)
    draw.line([(cx2 - 16, cy + 16), (cx2 + 16, cy - 16)], fill=accent, width=6)


def deco_map_pins(draw, accent):
    pts = [(150, 190), (430, 120), (700, 180), (930, 130)]
    for i in range(len(pts) - 1):
        x1, y1 = pts[i]
        x2, y2 = pts[i + 1]
        steps = 14
        for s in range(steps):
            if s % 2 == 0:
                t1 = s / steps
                t2 = (s + 1) / steps
                draw.line([
                    (x1 + (x2 - x1) * t1, y1 + (y2 - y1) * t1),
                    (x1 + (x2 - x1) * t2, y1 + (y2 - y1) * t2),
                ], fill=accent, width=3)
    for (x, y) in pts:
        draw.ellipse([x - 10, y - 10, x + 10, y + 10], fill=accent)
        draw.polygon([(x - 10, y + 2), (x + 10, y + 2), (x, y + 22)], fill=accent)


def deco_camera_corners(draw, accent):
    m = 46
    length = 60
    width = 5
    corners = [
        ((m, m), (1, 0), (0, 1)),
        ((IMG_SIZE - m, m), (-1, 0), (0, 1)),
        ((m, IMG_SIZE - m), (1, 0), (0, -1)),
        ((IMG_SIZE - m, IMG_SIZE - m), (-1, 0), (0, -1)),
    ]
    for (x, y), dx, dy in corners:
        draw.line([(x, y), (x + dx[0] * length, y + dx[1] * length)], fill=accent, width=width)
        draw.line([(x, y), (x + dy[0] * length, y + dy[1] * length)], fill=accent, width=width)
    cx, cy, r = IMG_SIZE // 2, 130, 26
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=accent, width=3)
    draw.ellipse([cx - 8, cy - 8, cx + 8, cy + 8], fill=accent)


DECORATIONS = {
    "compass": deco_compass,
    "lightning_split": deco_lightning_split,
    "check_cross": deco_check_cross,
    "map_pins": deco_map_pins,
    "camera_corners": deco_camera_corners,
}


def render_image(content: str, image_prompt: str, card_key: str, output_path: str):
    card = CARD_TYPES[card_key]

    photo = fetch_background_photo(image_prompt)
    if photo is not None:
        img = apply_photo_overlay(photo)
        print("[INFO] Using Pollinations photo background.")
    else:
        img = build_gradient_background(card)
        print("[INFO] Using gradient background (fallback).")

    img = img.convert("RGBA")

    deco_layer = Image.new("RGBA", (IMG_SIZE, IMG_SIZE), (0, 0, 0, 0))
    deco_draw = ImageDraw.Draw(deco_layer)
    glossy_accent = card["accent"] + (175,)
    DECORATIONS[card["decoration"]](deco_draw, glossy_accent)
    deco_layer = deco_layer.filter(ImageFilter.GaussianBlur(1.3))
    img = Image.alpha_composite(img, deco_layer)

    draw = ImageDraw.Draw(img)

    top_label_font = font("Poppins-SemiBold.ttf", 30)
    top_label = card['label'].upper()
    tb = draw.textbbox((0, 0), top_label, font=top_label_font)
    tw, th = tb[2] - tb[0], tb[3] - tb[1]
    pad_x, pad_y = 26, 14
    pill_x0 = IMG_SIZE / 2 - tw / 2 - pad_x
    pill_x1 = IMG_SIZE / 2 + tw / 2 + pad_x
    pill_y0 = 250
    pill_y1 = pill_y0 + th + pad_y * 2

    pill_layer = Image.new("RGBA", (IMG_SIZE, IMG_SIZE), (0, 0, 0, 0))
    pill_draw = ImageDraw.Draw(pill_layer)
    pill_radius = (pill_y1 - pill_y0) / 2
    pill_draw.rounded_rectangle([pill_x0, pill_y0, pill_x1, pill_y1], radius=pill_radius,
                                 fill=(0, 0, 0, 140), outline=card["accent"] + (110,), width=2)
    pill_layer = pill_layer.filter(ImageFilter.GaussianBlur(0.6))
    img = Image.alpha_composite(img, pill_layer)
    draw = ImageDraw.Draw(img)

    draw_centered_single(draw, top_label, top_label_font, IMG_SIZE / 2, pill_y0 + pad_y - 4,
                          (255, 255, 255), shadow=False)

    content_font_size = 58 if len(content) < 70 else (48 if len(content) < 120 else 40)
    fnt = font(card["quote_font"], content_font_size)

    max_text_width = IMG_SIZE - 220
    lines = wrap_text(draw, content, fnt, max_text_width)
    center_y = IMG_SIZE / 2 + 20
    draw_centered_multiline(draw, lines, fnt, IMG_SIZE / 2, center_y, card["text_color"])

    bbox_all = [draw.textbbox((0, 0), line, font=fnt) for line in lines]
    total_h = sum((b[3] - b[1]) * 1.35 for b in bbox_all)
    divider_y = center_y + total_h / 2 + 45
    draw.line([(IMG_SIZE / 2 - 44, divider_y), (IMG_SIZE / 2 + 44, divider_y)], fill=card["accent"], width=4)

    cta_font = font("Poppins-Bold.ttf", 34)
    draw_centered_single(draw, card["cta_plain"], cta_font, IMG_SIZE / 2, divider_y + 30, (255, 255, 255))

    brand_font = font("Poppins-Bold.ttf", 24)
    brand_text = "TRAVEL • NATURE • PLACES ON EARTH"
    draw_centered_single(draw, brand_text, brand_font, IMG_SIZE / 2, IMG_SIZE - 70, (255, 255, 255), shadow=True)

    img = img.convert("RGB")
    img.save(output_path, quality=95)
    print(f"Saved: {output_path}")


def pick_card_type() -> str:
    forced = os.environ.get("CARD_TYPE")
    if forced:
        if forced not in CARD_TYPES:
            print(f"[ERROR] Unknown CARD_TYPE '{forced}'. Available: {', '.join(CARD_TYPES)}")
            sys.exit(1)
        return forced

    STATE_DIR.mkdir(exist_ok=True)
    order = list(CARD_TYPES.keys())

    last_index = -1
    if os.path.exists(CARD_STATE_FILE):
        try:
            with open(CARD_STATE_FILE) as f:
                state = json.load(f)
            last_key = state.get("last_card")
            if last_key in order:
                last_index = order.index(last_key)
            else:
                last_index = state.get("last_index", -1)
        except Exception:
            pass

    next_index = (last_index + 1) % len(order)
    card_key = order[next_index]

    with open(CARD_STATE_FILE, "w") as f:
        json.dump({"last_card": card_key, "last_index": next_index}, f)

    return card_key


def build_caption(card_key: str, content: str) -> str:
    card = CARD_TYPES[card_key]
    tags = TAGS_BY_TYPE.get(card_key, "")
    return f"{content}\n\n{card['cta']}\n\n{tags}".strip()


def cleanup_generated_files():
    for path in (OUTPUT_IMAGE,):
        try:
            if os.path.exists(path):
                os.remove(path)
                print(f"[INFO] Cleaned up: {path}")
        except Exception as e:
            print(f"[WARN] Cleanup failed for {path}: {e}")


def run_image_post(dry_run: bool):
    ensure_fonts()
    card_key = pick_card_type()
    print(f"[INFO] Card type: {card_key}")

    content, image_prompt = generate_content(card_key)
    print(f"[INFO] Content: {content}")
    print(f"[INFO] Image prompt: {image_prompt}")

    render_image(content, image_prompt, card_key, OUTPUT_IMAGE)
    caption = build_caption(card_key, content)

    try:
        if dry_run:
            print("Dry run, not posting.")
            return True
        print("Uploading image to public temp host...")
        public_url = upload_to_uguu(OUTPUT_IMAGE)
        print("Creating Buffer post...")
        post = buffer_create_post(caption, media_url=public_url, media_type="image")
        print(f"Buffered post id: {post.get('id')} (queued via Buffer, will publish on schedule)")
        return True
    finally:
        cleanup_generated_files()


# ===========================================================================
# TYPE "video" — TikTok repost from @naturevibes689
# ===========================================================================

TIKTOK_PROFILE = "naturevibes689"
VIDEO_GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
DEDUPE_DIR = pathlib.Path(os.environ.get("DEDUPE_DIR", "dedupe"))
VIDEO_STATE_FILE = DEDUPE_DIR / os.environ.get("STATE_FILE", "state.json")
TMP_DIR = pathlib.Path("tmp_videos")
PAGE_SIZE = 5
MAX_PAGES_PER_RUN = 5


def _ydl_opts(**extra):
    opts = {
        "quiet": True,
        "no_warnings": True,
        "skip_download": True,
        "http_headers": {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            )
        },
    }
    opts.update(extra)
    return opts


def load_video_state():
    DEDUPE_DIR.mkdir(parents=True, exist_ok=True)
    if VIDEO_STATE_FILE.exists():
        with open(VIDEO_STATE_FILE, "r", encoding="utf-8") as f:
            state = json.load(f)
    else:
        state = {}
    state.setdefault("cursor", 0)
    state.setdefault("posted_ids", [])
    return state


def save_video_state(state):
    DEDUPE_DIR.mkdir(parents=True, exist_ok=True)
    with open(VIDEO_STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)


def list_profile_videos(profile):
    url = f"https://www.tiktok.com/@{profile}"
    with yt_dlp.YoutubeDL(_ydl_opts(extract_flat=True)) as ydl:
        info = ydl.extract_info(url, download=False)
    entries = info.get("entries") or []
    videos = []
    for e in entries:
        vid = e.get("id")
        if not vid:
            continue
        videos.append({
            "id": vid,
            "url": e.get("url") or e.get("webpage_url") or f"https://www.tiktok.com/@{profile}/video/{vid}",
        })
    return videos


def fetch_video_meta(video_url):
    with yt_dlp.YoutubeDL(_ydl_opts()) as ydl:
        info = ydl.extract_info(video_url, download=False)
    caption = (info.get("description") or info.get("title") or "").strip()
    return {"caption": caption}


def find_candidates(profile, vstate):
    all_videos = list_profile_videos(profile)
    if not all_videos:
        return [], True

    total = len(all_videos)
    cursor = vstate["cursor"]
    posted = set(vstate["posted_ids"])

    for _ in range(MAX_PAGES_PER_RUN):
        if cursor >= total:
            vstate["cursor"] = cursor
            return [], True

        page = all_videos[cursor:cursor + PAGE_SIZE]
        unposted = [v for v in page if v["id"] not in posted]

        if unposted:
            vstate["cursor"] = cursor
            candidates = []
            for v in unposted:
                meta = fetch_video_meta(v["url"])
                candidates.append({"id": v["id"], "caption": meta["caption"], "url": v["url"]})
            return candidates, False

        cursor += len(page)
        vstate["cursor"] = cursor
        if cursor >= total:
            return [], True

    return [], False


def download_video(video_url, dest_path):
    opts = _ydl_opts(
        skip_download=False,
        outtmpl=str(dest_path),
        format="bestvideo*+bestaudio/best",
        format_sort=["res", "fps", "br"],
        merge_output_format="mp4",
    )
    with yt_dlp.YoutubeDL(opts) as ydl:
        ydl.download([video_url])
    return dest_path


# Fallback captions — used ONLY when the original TikTok caption has no
# usable text AND no hashtags (nothing for Groq to work with at all).
VIDEO_FALLBACK_CAPTIONS = [
    "Nature never stops putting on a show.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #MustWatch",
    "Some views make you forget everything else.\n\n#NatureVibes #EarthPix #WildEarth #NaturePhotography #MustWatch",
    "This is the planet doing what it does best.\n\n#NatureLovers #WildEarth #EarthPix #NatureVibes #Breathtaking",
    "Untouched, wild, and absolutely stunning.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #MustWatch",
    "Moments like this remind you how wild the world is.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #Untamed",
    "The wild doesn't need a filter.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #Breathtaking",
    "Earth really outdid itself with this one.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #MustWatch",
    "Pure, raw, untamed nature.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #Untamed",
    "Some sights are worth stopping for.\n\n#NatureLovers #EarthPix #WildEarth #NatureVibes #Breathtaking",
    "This is what wild really looks like.\n\n#NatureUnfiltered #WildEarth #EarthPix #NatureVibes #MustWatch",
]


def pick_video_fallback_caption():
    return random.choice(VIDEO_FALLBACK_CAPTIONS)


def generate_video_caption(original_caption, groq_key, model=VIDEO_GROQ_MODEL, max_words=15, max_attempts=3):
    original_caption = (original_caption or "").strip()
    hashtags_found = re.findall(r"#\w+", original_caption)
    text_only = re.sub(r"#\w+", "", original_caption).strip()
    text_only = re.sub(r"\s{2,}", " ", text_only)

    if not text_only and not hashtags_found:
        print("[INFO] No usable text or hashtags in source caption — using fallback caption.")
        return pick_video_fallback_caption()

    if not text_only and hashtags_found:
        source_block = (
            "The original caption had NO descriptive sentence — only these "
            "hashtags: " + " ".join(hashtags_found) + "\n"
            "Use these hashtags ONLY as a clue to figure out the video's topic/theme, "
            "then write a natural caption about that theme. Do not mention that "
            "hashtags were your source."
        )
    else:
        source_block = f"ORIGINAL CAPTION:\n{original_caption}"

    base_prompt = (
        "You are a social media caption writer. You will be given the ORIGINAL "
        "caption from a TikTok video (any topic/niche — news, devotional, motivation, "
        "comedy, film clip, etc). Rewrite it for Facebook/Instagram in the SAME "
        "language/tone as the original (if it's Hindi/Hinglish, reply in Hindi/Hinglish; "
        "if English, reply in English). Output in this EXACT format:\n\n"
        "<one punchy caption sentence>\n"
        "\n"
        "#hashtag1\n#hashtag2\n#hashtag3\n#hashtag4\n#hashtag5\n\n"
        "Strict rules:\n"
        f"- Line 1 is ONE sentence, MAXIMUM {max_words} words (count carefully — "
        "9 or 10 words is ideal, never go over the limit).\n"
        "- No emojis, no digits/numbers, in line 1.\n"
        "- Do NOT invent facts not present in the original caption.\n"
        "- Do NOT mention TikTok, any username/handle, video ID, or any TikTok-related "
        "word anywhere — the sentence must read naturally with no gaps or leftover "
        "words if such a mention were ever removed.\n"
        "- Then a blank line, then EXACTLY 5 hashtags, one per line.\n"
        "- Hashtags must be SEO-relevant to the actual content/niche of this video "
        "(not generic filler like #viral #trending #fyp) — think what someone would "
        "actually search to find this content. No spaces, no numbers, no repeats, "
        "no # symbol duplicated.\n"
        "- Output ONLY the caption + hashtags, nothing else (no preamble, no quotes, "
        "no explanation).\n\n"
        f"{source_block}"
    )

    prompt = base_prompt
    body_raw, hashtag_lines = "", []

    for attempt in range(1, max_attempts + 1):
        r = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {groq_key}"},
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.7,
                "max_tokens": 150,
            },
            timeout=30,
        )
        r.raise_for_status()
        raw = r.json()["choices"][0]["message"]["content"].strip()
        body_raw, hashtag_lines = split_caption(raw)

        if has_forbidden_terms(body_raw):
            prompt = (
                base_prompt
                + "\n\nYour previous attempt mentioned TikTok, a video ID, a handle, "
                  "or a number in line 1. Rewrite line 1 from scratch as a natural "
                  "sentence with NO such mentions and no leftover gaps."
            )
            continue

        body = clean_body(body_raw)
        if body and len(body.split()) <= max_words:
            break

        prompt = (
            base_prompt
            + f"\n\nYour previous attempt was too long. Rewrite line 1 to be "
              f"{max_words} words or fewer, same meaning, same format."
        )
    else:
        body = clean_body(body_raw)
        words = body.split()
        if len(words) > max_words:
            words = words[:max_words]
        body = tidy_dangling(" ".join(words))

    hashtags = clean_hashtags(hashtag_lines)
    if not hashtags:
        hashtags = fallback_hashtags(original_caption)

    return f"{body}\n\n" + "\n".join(hashtags)


def has_forbidden_terms(text):
    if re.search(r"(?i)\btik\s?tok\b", text):
        return True
    if re.search(r"(?i)\b(video|clip|post|reel)?\s*id\b", text):
        return True
    if re.search(r"@\w+", text):
        return True
    if re.search(r"\d", text):
        return True
    return False


def split_caption(raw):
    lines = [l.strip() for l in raw.splitlines() if l.strip()]
    body_lines, hashtag_lines = [], []
    for l in lines:
        if l.startswith("#"):
            hashtag_lines.append(l)
        else:
            body_lines.append(l)
    return " ".join(body_lines).strip(), hashtag_lines


def clean_body(body_raw):
    text = re.sub(r"(?i)\btik\s?tok\b", "", body_raw)
    text = re.sub(r"(?i)\b(video|clip|post|reel)?\s*id\b", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\s+([.,!?])", r"\1", text).strip()

    match = re.search(r"[^.!?]+[.!?]?", text)
    if match:
        text = match.group(0).strip()
    return text


def tidy_dangling(text):
    edge_words = {"by", "from", "on", "in", "at", "with", "to", "of", "the",
                  "a", "an", "and", "or", "this", "that", "for"}
    words = text.split()
    while words and words[-1].strip(".,!?").lower() in edge_words:
        words.pop()
    while words and words[0].lower() in edge_words:
        words.pop(0)
    text = " ".join(words).strip()
    if text:
        text = text[0].upper() + text[1:]
        if text[-1] not in ".!?":
            text += "."
    return text


def clean_hashtags(hashtag_lines):
    hashtags = []
    for l in hashtag_lines:
        hashtags.extend(re.findall(r"#\w+", l))

    seen, clean_tags = set(), []
    for h in hashtags:
        h = re.sub(r"[^A-Za-z#]", "", h)
        if len(h) > 1 and h.lower() not in seen:
            seen.add(h.lower())
            clean_tags.append(h)
    return clean_tags[:5]


def fallback_hashtags(original_caption):
    words = re.findall(r"[A-Za-z]{4,}", original_caption or "")
    stop = {"this", "that", "with", "from", "your", "have", "will", "just",
            "what", "when", "they", "them", "video", "watch", "tiktok"}
    seen, tags = set(), []
    for w in words:
        wl = w.lower()
        if wl in stop or wl in seen:
            continue
        seen.add(wl)
        tags.append("#" + w.capitalize())
        if len(tags) == 5:
            break
    generic_pool = ["#Explore", "#DailyDose", "#MustWatch", "#Highlights", "#ForYou"]
    for g in generic_pool:
        if len(tags) >= 5:
            break
        if g.lower() not in seen:
            seen.add(g.lower())
            tags.append(g)
    return tags[:5]


def run_video_post(dry_run: bool) -> bool:
    TMP_DIR.mkdir(exist_ok=True)
    vstate = load_video_state()
    print(f"Checking @{TIKTOK_PROFILE} from cursor {vstate['cursor']}")
    candidates, exhausted = find_candidates(TIKTOK_PROFILE, vstate)

    if exhausted and not candidates:
        print(f"  @{TIKTOK_PROFILE} fully exhausted, resetting cursor")
        vstate["cursor"] = 0
    save_video_state(vstate)

    if not candidates:
        print("No postable video this run.")
        return False

    posted = False
    for v in candidates:
        vid, tt_caption = v["id"], v["caption"]
        video_path = TMP_DIR / f"{vid}.mp4"
        print(f"\nVideo {vid} (@{TIKTOK_PROFILE})")

        try:
            download_video(v["url"], video_path)
            print(f"Original TikTok caption: {tt_caption!r}")
            caption = generate_video_caption(tt_caption, GROQ_API_KEY)
            print(f"Caption: {caption}")

            if dry_run:
                print("Dry run, not posting.")
            else:
                print("Uploading video to public temp host...")
                public_url = upload_to_uguu(video_path)
                print("Creating Buffer post...")
                post = buffer_create_post(caption, media_url=public_url, media_type="video")
                print(f"Buffered post id: {post.get('id')} (queued via Buffer, will publish on schedule)")

            vstate["posted_ids"].append(vid)
            save_video_state(vstate)
            posted = True

        except Exception as e:
            print(f"Failed: {e}")
        finally:
            if video_path.exists():
                video_path.unlink()

        if posted:
            break

    try:
        TMP_DIR.rmdir()
    except OSError:
        pass

    return posted


# ===========================================================================
# Alternation + main
# ===========================================================================

def pick_post_type(forced=None) -> str:
    if forced:
        return forced

    STATE_DIR.mkdir(exist_ok=True)
    last_type = None
    if POST_TYPE_STATE_FILE.exists():
        try:
            with open(POST_TYPE_STATE_FILE) as f:
                last_type = json.load(f).get("last_type")
        except Exception:
            pass

    next_type = "video" if last_type != "video" else "image"
    with open(POST_TYPE_STATE_FILE, "w") as f:
        json.dump({"last_type": next_type}, f)
    return next_type


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Fetch/generate only, don't post")
    parser.add_argument("--force-type", choices=["image", "video"], default=None,
                         help="Skip alternation, force this run's content type")
    args = parser.parse_args()

    check_env()

    post_type = pick_post_type(args.force_type)
    print(f"[INFO] This run's content type: {post_type}")

    if post_type == "image":
        ok = run_image_post(args.dry_run)
    else:
        ok = run_video_post(args.dry_run)
        if not ok and not args.dry_run:
            # video source had nothing new this run -> don't waste the run,
            # fall back to an image post so the page still posts something
            print("[INFO] No new video available, falling back to image post for this run.")
            ok = run_image_post(args.dry_run)

    print("Done." if ok else "Nothing posted this run.")


if __name__ == "__main__":
    main()
